/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class BankAccount */

#ifndef _Included_BankAccount
#define _Included_BankAccount
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     BankAccount
 * Method:    getNumber
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_BankAccount_getNumber
  (JNIEnv *, jobject, jint);

/*
 * Class:     BankAccount
 * Method:    getName
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_BankAccount_getName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     BankAccount
 * Method:    getBalance
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_BankAccount_getBalance
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     BankAccount
 * Method:    depositCash
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_BankAccount_depositCash
  (JNIEnv *, jobject, jdouble);

#ifdef __cplusplus
}
#endif
#endif
